In [1]:
import pandas as pd
import numpy as np
import requests
import datetime
import sys
from datetime import date
import re

In [2]:
raw_df = pd.read_csv(r'Weather_raw df.csv')
raw_df.head(10)

,Unnamed: 0,LOCALITA,DATA,TMEDIA Â°C,TMIN Â°C,TMAX Â°C,PUNTORUGIADA Â°C,UMIDITA %,VISIBILITA km,VENTOMEDIA km/h,VENTOMAX km/h,RAFFICA km/h,PRESSIONESLM mb,PRESSIONEMEDIA mb,PIOGGIA mm,FENOMENI
0,0,Verona,1/1/2003,"""5,6""","""3""","""8""","""4,6""","""93""","""4""","""3""","""11""","""0""","""0""","""0""","""0""","""nebbia """
1,1,Verona,2/1/2003,"""4,8""","""4""","""6""","""3,9""","""94""","""2""","""6""","""11""","""0""","""0""","""0""","""0""","""pioggia nebbia """
2,2,Verona,3/1/2003,"""5,4""","""4""","""9""","""4,4""","""93""","""3""","""9""","""13""","""0""","""0""","""0""","""0""","""nebbia """
3,3,Verona,4/1/2003,"""4,4""","""1,8""","""5,4""","""3,4""","""93""","""1""","""5""","""11""","""0""","""0""","""0""","""0""","""nebbia """
4,4,Verona,5/1/2003,"""4,7""","""2,9""","""7,1""","""3,3""","""91""","""6""","""8""","""26""","""0""","""0""","""0""","""7,6""","""pioggia nebbia """
5,5,Verona,6/1/2003,"""4,3""","""2,1""","""7,2""","""2,6""","""89""","""11""","""9""","""18""","""0""","""0""","""0""","""0""","""pioggia """
6,6,Verona,7/1/2003,"""2,1""","""0,6""","""4,2""","""1,2""","""94""","""4""","""7""","""15""","""0""","""0""","""0""","""11,2""","""pioggia neve nebbia """
7,7,Verona,8/1/2003,"""1,2""","""0,9""","""2,2""","""0,4""","""94""","""4""","""5""","""11""","""0""","""0""","""0""","""1""","""pioggia neve """
8,8,Verona,9/1/2003,"""1,3""","""0,5""","""2,1""","""0,4""","""94""","""4""","""6""","""9""","""0""","""0""","""0""","""1""","""pioggia neve """
9,9,Verona,10/1/2003,"""0,8""","""-1""","""2,4""","""0""","""0""","""3""","""3""","""8""","""0""","""0""","""0""","""0""",""""""

In [3]:
raw_df.drop(columns= 'Unnamed: 0', axis=0, inplace=True)
raw_df.head()

,LOCALITA,DATA,TMEDIA Â°C,TMIN Â°C,TMAX Â°C,PUNTORUGIADA Â°C,UMIDITA %,VISIBILITA km,VENTOMEDIA km/h,VENTOMAX km/h,RAFFICA km/h,PRESSIONESLM mb,PRESSIONEMEDIA mb,PIOGGIA mm,FENOMENI
0,Verona,1/1/2003,"""5,6""","""3""","""8""","""4,6""","""93""","""4""","""3""","""11""","""0""","""0""","""0""","""0""","""nebbia """
1,Verona,2/1/2003,"""4,8""","""4""","""6""","""3,9""","""94""","""2""","""6""","""11""","""0""","""0""","""0""","""0""","""pioggia nebbia """
2,Verona,3/1/2003,"""5,4""","""4""","""9""","""4,4""","""93""","""3""","""9""","""13""","""0""","""0""","""0""","""0""","""nebbia """
3,Verona,4/1/2003,"""4,4""","""1,8""","""5,4""","""3,4""","""93""","""1""","""5""","""11""","""0""","""0""","""0""","""0""","""nebbia """
4,Verona,5/1/2003,"""4,7""","""2,9""","""7,1""","""3,3""","""91""","""6""","""8""","""26""","""0""","""0""","""0""","""7,6""","""pioggia nebbia """

In [4]:
# print(raw_df.columns)

In [5]:
raw_df.rename(columns={'LOCALITA': 'City', 'DATA': 'Date', 'TMEDIA Â°C': 'AVG Temperature °C',\
    'TMIN Â°C':'MIN Temp °C','TMAX Â°C':'MAX Temp °C', 'PUNTORUGIADA Â°C' : 'Dew point' ,\
    'UMIDITA %':'Humidity', 'VISIBILITA km':'Visibility km', 'VENTOMEDIA km/h':'AVG Wind km/h' ,\
    'VENTOMAX km/h':'MAX Wind km/h' , 'RAFFICA km/h':'Wind gust km/h' , \
    'PRESSIONESLM mb': 'Pressure mb' , 'PRESSIONEMEDIA mb':'AVG Pressure mb' , 'PIOGGIA mm':'Rain mm' , 'FENOMENI':'Phenomenas'}, inplace=True)

In [6]:
# print(raw_df.columns)

In [7]:
def clean_func(df):
    return df.str.replace('\"', '')

raw_df= raw_df.apply(clean_func)
raw_df.head()

,City,Date,AVG Temperature °C,MIN Temp °C,MAX Temp °C,Dew point,Humidity,Visibility km,AVG Wind km/h,MAX Wind km/h,Wind gust km/h,Pressure mb,AVG Pressure mb,Rain mm,Phenomenas
0,Verona,1/1/2003,"5,6",3,8,"4,6",93,4,3,11,0,0,0,0,nebbia
1,Verona,2/1/2003,"4,8",4,6,"3,9",94,2,6,11,0,0,0,0,pioggia nebbia
2,Verona,3/1/2003,"5,4",4,9,"4,4",93,3,9,13,0,0,0,0,nebbia
3,Verona,4/1/2003,"4,4","1,8","5,4","3,4",93,1,5,11,0,0,0,0,nebbia
4,Verona,5/1/2003,"4,7","2,9","7,1","3,3",91,6,8,26,0,0,0,"7,6",pioggia nebbia

In [8]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7306 entries, 0 to 7305
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   City                7305 non-null   object
 1   Date                7305 non-null   object
 2   AVG Temperature °C  7265 non-null   object
 3   MIN Temp °C         7265 non-null   object
 4   MAX Temp °C         7265 non-null   object
 5   Dew point           7265 non-null   object
 6   Humidity            7265 non-null   object
 7   Visibility km       7265 non-null   object
 8   AVG Wind km/h       7265 non-null   object
 9   MAX Wind km/h       7265 non-null   object
 10  Wind gust km/h      7265 non-null   object
 11  Pressure mb         7265 non-null   object
 12  AVG Pressure mb     7265 non-null   object
 13  Rain mm             7265 non-null   object
 14  Phenomenas          7265 non-null   object
dtypes: object(15)
memory usage: 856.3+ KB

In [9]:
raw_df['Date'] = pd.to_datetime(raw_df['Date'], format='%d/%m/%Y')

In [10]:
print(raw_df.iloc[:,2:-1].head(10))

  AVG Temperature °C MIN Temp °C MAX Temp °C Dew point Humidity Visibility km  \
0                5,6           3           8       4,6       93             4
1                4,8           4           6       3,9       94             2
2                5,4           4           9       4,4       93             3
3                4,4         1,8         5,4       3,4       93             1
4                4,7         2,9         7,1       3,3       91             6
5                4,3         2,1         7,2       2,6       89            11
6                2,1         0,6         4,2       1,2       94             4
7                1,2         0,9         2,2       0,4       94             4
8                1,3         0,5         2,1       0,4       94             4
9                0,8          -1         2,4         0        0             3

  AVG Wind km/h MAX Wind km/h Wind gust km/h Pressure mb AVG Pressure mb  \
0             3            11              0           0               0
1             6            11              0           0               0
2             9            13              0           0               0
3             5            11              0           0               0
4             8            26              0           0               0
5             9            18              0           0               0
6             7            15              0           0               0
7             5            11              0           0               0
8             6             9              0           0               0
9             3             8              0           0               0

  Rain mm
0       0
1       0
2       0
3       0
4     7,6
5       0
6    11,2
7       1
8       1
9       0

In [11]:
raw_df_null = raw_df[(raw_df['AVG Temperature °C'].isnull()) & (raw_df['MIN Temp °C'].isnull()) &\
                        (raw_df['MAX Temp °C'].isnull()) & (raw_df['Dew point'].isnull()) &\
                            (raw_df['Humidity'].isnull()) & (raw_df['Visibility km'].isnull()) &\
                                (raw_df['AVG Wind km/h'].isnull()) & (raw_df['MAX Wind km/h'].isnull()) &\
                                    (raw_df['Wind gust km/h'].isnull()) & (raw_df['Pressure mb'].isnull()) &\
                                        (raw_df['AVG Pressure mb'].isnull()) & (raw_df['Rain mm'].isnull())]

In [12]:
raw_df_null

,City,Date,AVG Temperature °C,MIN Temp °C,MAX Temp °C,Dew point,Humidity,Visibility km,AVG Wind km/h,MAX Wind km/h,Wind gust km/h,Pressure mb,AVG Pressure mb,Rain mm,Phenomenas
1047,Verona,2005-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048,Verona,2005-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049,Verona,2005-11-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050,Verona,2005-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1051,Verona,2005-11-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1052,Verona,2005-11-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1053,Verona,2005-11-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1054,Verona,2005-11-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1055,Verona,2005-11-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1056,Verona,2005-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1057,Verona,2005-11-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1058,Verona,2005-11-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,Verona,2005-11-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,Verona,2005-11-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1061,Verona,2005-11-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,Verona,2005-11-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1063,Verona,2005-11-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1064,Verona,2005-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1700,Verona,2007-08-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1801,Verona,2007-12-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2126,Verona,2008-10-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2538,Verona,2009-12-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2539,Verona,2009-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3273,Verona,2011-12-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3276,Verona,2011-12-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3464,Verona,2012-06-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3735,Verona,2013-03-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4196,Verona,2014-06-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4385,Verona,2015-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4616,Verona,2015-08-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4854,Verona,2016-04-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5139,Verona,2017-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5879,Verona,2019-02-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6588,Verona,2021-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6850,Verona,2021-10-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6851,Verona,2021-10-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6852,Verona,2021-10-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6853,Verona,2021-10-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6854,Verona,2021-10-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6855,Verona,2021-10-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7305,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
raw_df_null.fillna(value='None')

,City,Date,AVG Temperature °C,MIN Temp °C,MAX Temp °C,Dew point,Humidity,Visibility km,AVG Wind km/h,MAX Wind km/h,Wind gust km/h,Pressure mb,AVG Pressure mb,Rain mm,Phenomenas
1047,Verona,2005-11-13 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1048,Verona,2005-11-14 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1049,Verona,2005-11-15 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1050,Verona,2005-11-16 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1051,Verona,2005-11-17 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1052,Verona,2005-11-18 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1053,Verona,2005-11-19 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1054,Verona,2005-11-20 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1055,Verona,2005-11-21 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1056,Verona,2005-11-22 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1057,Verona,2005-11-23 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1058,Verona,2005-11-24 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1059,Verona,2005-11-25 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1060,Verona,2005-11-26 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1061,Verona,2005-11-27 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1062,Verona,2005-11-28 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1063,Verona,2005-11-29 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1064,Verona,2005-11-30 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1700,Verona,2007-08-28 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
1801,Verona,2007-12-07 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
2126,Verona,2008-10-27 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
2538,Verona,2009-12-13 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
2539,Verona,2009-12-14 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
3273,Verona,2011-12-18 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
3276,Verona,2011-12-21 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
3464,Verona,2012-06-26 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
3735,Verona,2013-03-24 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
4196,Verona,2014-06-28 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
4385,Verona,2015-01-03 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
4616,Verona,2015-08-22 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
4854,Verona,2016-04-16 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
5139,Verona,2017-01-26 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
5879,Verona,2019-02-05 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6588,Verona,2021-01-14 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6850,Verona,2021-10-03 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6851,Verona,2021-10-04 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6852,Verona,2021-10-05 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6853,Verona,2021-10-06 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6854,Verona,2021-10-07 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
6855,Verona,2021-10-08 00:00:00,None,None,None,None,None,None,None,None,None,None,None,None,None
7305,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [14]:
def clean_col(col, dtype):
    return col.str.replace(',','.', regex=False).astype(dtype , errors='ignore')

In [15]:
# .astype(dtype , errors='ignore')

In [16]:
raw_df['AVG Temperature °C'] = clean_col(raw_df['AVG Temperature °C'], dtype='float64')
raw_df['MIN Temp °C'] = clean_col(raw_df['MIN Temp °C'], dtype='float64')
raw_df['MAX Temp °C'] = clean_col(raw_df['MAX Temp °C'], dtype='float64')
raw_df['Dew point'] = clean_col(raw_df['Dew point'], dtype='float64')
raw_df['Humidity'] = clean_col(raw_df['Humidity'], dtype='float64')
raw_df['AVG Wind km/h'] = clean_col(raw_df['AVG Wind km/h'], dtype=pd.Int64Dtype())
raw_df['MAX Wind km/h'] = clean_col(raw_df['MAX Wind km/h'],  dtype=pd.Int64Dtype())
raw_df['Wind gust km/h'] = clean_col(raw_df['Wind gust km/h'], dtype=pd.Int64Dtype())
raw_df['Pressure mb'] = clean_col(raw_df['Pressure mb'], dtype='float64')
raw_df['AVG Pressure mb'] = clean_col(raw_df['AVG Pressure mb'], dtype='float64')
raw_df['Rain mm'] = clean_col(raw_df['Rain mm'], dtype='float64')
raw_df['Visibility km'] = clean_col(raw_df['Visibility km'], dtype=pd.Int64Dtype())

In [17]:
raw_df.head()

,City,Date,AVG Temperature °C,MIN Temp °C,MAX Temp °C,Dew point,Humidity,Visibility km,AVG Wind km/h,MAX Wind km/h,Wind gust km/h,Pressure mb,AVG Pressure mb,Rain mm,Phenomenas
0,Verona,2003-01-01,5.6,3.0,8.0,4.6,93.0,4,3,11,0,0.0,0.0,0.0,nebbia
1,Verona,2003-01-02,4.8,4.0,6.0,3.9,94.0,2,6,11,0,0.0,0.0,0.0,pioggia nebbia
2,Verona,2003-01-03,5.4,4.0,9.0,4.4,93.0,3,9,13,0,0.0,0.0,0.0,nebbia
3,Verona,2003-01-04,4.4,1.8,5.4,3.4,93.0,1,5,11,0,0.0,0.0,0.0,nebbia
4,Verona,2003-01-05,4.7,2.9,7.1,3.3,91.0,6,8,26,0,0.0,0.0,7.6,pioggia nebbia

In [18]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7306 entries, 0 to 7305
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   City                7305 non-null   object
 1   Date                7305 non-null   datetime64[ns]
 2   AVG Temperature °C  7265 non-null   float64
 3   MIN Temp °C         7265 non-null   float64
 4   MAX Temp °C         7265 non-null   float64
 5   Dew point           7265 non-null   float64
 6   Humidity            7265 non-null   float64
 7   Visibility km       7265 non-null   Int64
 8   AVG Wind km/h       7265 non-null   Int64
 9   MAX Wind km/h       7265 non-null   Int64
 10  Wind gust km/h      7265 non-null   Int64
 11  Pressure mb         7265 non-null   float64
 12  AVG Pressure mb     7265 non-null   float64
 13  Rain mm             7265 non-null   float64
 14  Phenomenas          7265 non-null   object
dtypes: Int64(4), datetime64[ns](1), float64(8), object(2)
memory usage: 884.8+ KB