In [1]:
# 1) import libraries
import pandas as pd
import numpy as np
import requests
import datetime
import sys
from datetime import date
import re

In [2]:
# 2) reading raw Data Frame for cleaning 
raw_df = pd.read_csv(r'Weather_raw df.csv')
raw_df.head(10)

,Unnamed: 0,LOCALITA,DATA,TMEDIA Â°C,TMIN Â°C,TMAX Â°C,PUNTORUGIADA Â°C,UMIDITA %,VISIBILITA km,VENTOMEDIA km/h,VENTOMAX km/h,RAFFICA km/h,PRESSIONESLM mb,PRESSIONEMEDIA mb,PIOGGIA mm,FENOMENI
0,0,Verona,1/1/2003,"""5,6""","""3""","""8""","""4,6""","""93""","""4""","""3""","""11""","""0""","""0""","""0""","""0""","""nebbia """
1,1,Verona,2/1/2003,"""4,8""","""4""","""6""","""3,9""","""94""","""2""","""6""","""11""","""0""","""0""","""0""","""0""","""pioggia nebbia """
2,2,Verona,3/1/2003,"""5,4""","""4""","""9""","""4,4""","""93""","""3""","""9""","""13""","""0""","""0""","""0""","""0""","""nebbia """
3,3,Verona,4/1/2003,"""4,4""","""1,8""","""5,4""","""3,4""","""93""","""1""","""5""","""11""","""0""","""0""","""0""","""0""","""nebbia """
4,4,Verona,5/1/2003,"""4,7""","""2,9""","""7,1""","""3,3""","""91""","""6""","""8""","""26""","""0""","""0""","""0""","""7,6""","""pioggia nebbia """
5,5,Verona,6/1/2003,"""4,3""","""2,1""","""7,2""","""2,6""","""89""","""11""","""9""","""18""","""0""","""0""","""0""","""0""","""pioggia """
6,6,Verona,7/1/2003,"""2,1""","""0,6""","""4,2""","""1,2""","""94""","""4""","""7""","""15""","""0""","""0""","""0""","""11,2""","""pioggia neve nebbia """
7,7,Verona,8/1/2003,"""1,2""","""0,9""","""2,2""","""0,4""","""94""","""4""","""5""","""11""","""0""","""0""","""0""","""1""","""pioggia neve """
8,8,Verona,9/1/2003,"""1,3""","""0,5""","""2,1""","""0,4""","""94""","""4""","""6""","""9""","""0""","""0""","""0""","""1""","""pioggia neve """
9,9,Verona,10/1/2003,"""0,8""","""-1""","""2,4""","""0""","""0""","""3""","""3""","""8""","""0""","""0""","""0""","""0""",""""""

In [3]:
# 3) delete column 'Unnamed' not useful
raw_df.drop(columns= 'Unnamed: 0', axis=0, inplace=True)
raw_df.head()

,LOCALITA,DATA,TMEDIA Â°C,TMIN Â°C,TMAX Â°C,PUNTORUGIADA Â°C,UMIDITA %,VISIBILITA km,VENTOMEDIA km/h,VENTOMAX km/h,RAFFICA km/h,PRESSIONESLM mb,PRESSIONEMEDIA mb,PIOGGIA mm,FENOMENI
0,Verona,1/1/2003,"""5,6""","""3""","""8""","""4,6""","""93""","""4""","""3""","""11""","""0""","""0""","""0""","""0""","""nebbia """
1,Verona,2/1/2003,"""4,8""","""4""","""6""","""3,9""","""94""","""2""","""6""","""11""","""0""","""0""","""0""","""0""","""pioggia nebbia """
2,Verona,3/1/2003,"""5,4""","""4""","""9""","""4,4""","""93""","""3""","""9""","""13""","""0""","""0""","""0""","""0""","""nebbia """
3,Verona,4/1/2003,"""4,4""","""1,8""","""5,4""","""3,4""","""93""","""1""","""5""","""11""","""0""","""0""","""0""","""0""","""nebbia """
4,Verona,5/1/2003,"""4,7""","""2,9""","""7,1""","""3,3""","""91""","""6""","""8""","""26""","""0""","""0""","""0""","""7,6""","""pioggia nebbia """

In [4]:
# print(raw_df.columns)

In [5]:
# 4) columns indexes translation from ITA to ENG
raw_df.rename(columns={'LOCALITA': 'City', 'DATA': 'Date', 'TMEDIA Â°C': 'AVG Temperature °C',\
    'TMIN Â°C':'MIN Temp °C','TMAX Â°C':'MAX Temp °C', 'PUNTORUGIADA Â°C' : 'Dew point' ,\
    'UMIDITA %':'Humidity', 'VISIBILITA km':'Visibility km', 'VENTOMEDIA km/h':'AVG Wind km/h' ,\
    'VENTOMAX km/h':'MAX Wind km/h' , 'RAFFICA km/h':'Wind gust km/h' , \
    'PRESSIONESLM mb': 'Pressure mb' , 'PRESSIONEMEDIA mb':'AVG Pressure mb' , 'PIOGGIA mm':'Rain mm' , 'FENOMENI':'Phenomenas'}, inplace=True)

In [6]:
# print(raw_df.columns)

In [7]:
# 5) create a function to replace character ( " )
def clean_func(df):
    return df.str.replace('\"', '')

raw_df= raw_df.apply(clean_func)
raw_df.head()

,City,Date,AVG Temperature °C,MIN Temp °C,MAX Temp °C,Dew point,Humidity,Visibility km,AVG Wind km/h,MAX Wind km/h,Wind gust km/h,Pressure mb,AVG Pressure mb,Rain mm,Phenomenas
0,Verona,1/1/2003,"5,6",3,8,"4,6",93,4,3,11,0,0,0,0,nebbia
1,Verona,2/1/2003,"4,8",4,6,"3,9",94,2,6,11,0,0,0,0,pioggia nebbia
2,Verona,3/1/2003,"5,4",4,9,"4,4",93,3,9,13,0,0,0,0,nebbia
3,Verona,4/1/2003,"4,4","1,8","5,4","3,4",93,1,5,11,0,0,0,0,nebbia
4,Verona,5/1/2003,"4,7","2,9","7,1","3,3",91,6,8,26,0,0,0,"7,6",pioggia nebbia

In [8]:
print(raw_df.shape)

(7306, 15)

In [9]:
# 6) check columns data format
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7306 entries, 0 to 7305
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   City                7305 non-null   object
 1   Date                7305 non-null   object
 2   AVG Temperature °C  7265 non-null   object
 3   MIN Temp °C         7265 non-null   object
 4   MAX Temp °C         7265 non-null   object
 5   Dew point           7265 non-null   object
 6   Humidity            7265 non-null   object
 7   Visibility km       7265 non-null   object
 8   AVG Wind km/h       7265 non-null   object
 9   MAX Wind km/h       7265 non-null   object
 10  Wind gust km/h      7265 non-null   object
 11  Pressure mb         7265 non-null   object
 12  AVG Pressure mb     7265 non-null   object
 13  Rain mm             7265 non-null   object
 14  Phenomenas          7265 non-null   object
dtypes: object(15)
memory usage: 856.3+ KB

In [10]:
# 7) change Date column format from object to date
raw_df['Date'] = pd.to_datetime(raw_df['Date'], format='%d/%m/%Y')

In [11]:
# 8) check all other columns which report only numeric datas 
print(raw_df.iloc[:,2:-1].head(10))

  AVG Temperature °C MIN Temp °C MAX Temp °C Dew point Humidity Visibility km  \
0                5,6           3           8       4,6       93             4
1                4,8           4           6       3,9       94             2
2                5,4           4           9       4,4       93             3
3                4,4         1,8         5,4       3,4       93             1
4                4,7         2,9         7,1       3,3       91             6
5                4,3         2,1         7,2       2,6       89            11
6                2,1         0,6         4,2       1,2       94             4
7                1,2         0,9         2,2       0,4       94             4
8                1,3         0,5         2,1       0,4       94             4
9                0,8          -1         2,4         0        0             3

  AVG Wind km/h MAX Wind km/h Wind gust km/h Pressure mb AVG Pressure mb  \
0             3            11              0           0               0
1             6            11              0           0               0
2             9            13              0           0               0
3             5            11              0           0               0
4             8            26              0           0               0
5             9            18              0           0               0
6             7            15              0           0               0
7             5            11              0           0               0
8             6             9              0           0               0
9             3             8              0           0               0

  Rain mm
0       0
1       0
2       0
3       0
4     7,6
5       0
6    11,2
7       1
8       1
9       0

In [12]:
# 9) look for empty rows - no datas are recorded in the Weather Archive
raw_df_null = raw_df[(raw_df['AVG Temperature °C'].isnull()) & (raw_df['MIN Temp °C'].isnull()) &\
                        (raw_df['MAX Temp °C'].isnull()) & (raw_df['Dew point'].isnull()) &\
                            (raw_df['Humidity'].isnull()) & (raw_df['Visibility km'].isnull()) &\
                                (raw_df['AVG Wind km/h'].isnull()) & (raw_df['MAX Wind km/h'].isnull()) &\
                                    (raw_df['Wind gust km/h'].isnull()) & (raw_df['Pressure mb'].isnull()) &\
                                        (raw_df['AVG Pressure mb'].isnull()) & (raw_df['Rain mm'].isnull())]

In [30]:
# 10) check all the indexes of the empty rows - decide not to drop the records because there won't be a right .fillna() method
raw_df_null.index

Int64Index([1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057,
            1058, 1059, 1060, 1061, 1062, 1063, 1064, 1700, 1801, 2126, 2538,
            2539, 3273, 3276, 3464, 3735, 4196, 4385, 4616, 4854, 5139, 5879,
            6588, 6850, 6851, 6852, 6853, 6854, 6855, 7305],
           dtype='int64')

In [14]:
# 11) drop last row totally empty
raw_df = raw_df.drop(index=7305, axis=1)

In [15]:
# 12) create a function to cast all the columns with the correct dtype - parameter " errors='ignore' " is added because of the NaNs value in the DF
def clean_col(col, dtype):
    return col.str.replace(',','.', regex=False).astype(dtype , errors='ignore')

In [16]:
# 13) executing columns cast - dtype 'pd.Int64Dtype' is used because Python struggles to cast into 'int64' when there are NaNs value in columns 
raw_df['AVG Temperature °C'] = clean_col(raw_df['AVG Temperature °C'], dtype='float64')
raw_df['MIN Temp °C'] = clean_col(raw_df['MIN Temp °C'], dtype='float64')
raw_df['MAX Temp °C'] = clean_col(raw_df['MAX Temp °C'], dtype='float64')
raw_df['Dew point'] = clean_col(raw_df['Dew point'], dtype='float64')
raw_df['Humidity'] = clean_col(raw_df['Humidity'], dtype='float64')
raw_df['AVG Wind km/h'] = clean_col(raw_df['AVG Wind km/h'], dtype=pd.Int64Dtype())
raw_df['MAX Wind km/h'] = clean_col(raw_df['MAX Wind km/h'],  dtype=pd.Int64Dtype())
raw_df['Wind gust km/h'] = clean_col(raw_df['Wind gust km/h'], dtype=pd.Int64Dtype())
raw_df['Pressure mb'] = clean_col(raw_df['Pressure mb'], dtype='float64')
raw_df['AVG Pressure mb'] = clean_col(raw_df['AVG Pressure mb'], dtype='float64')
raw_df['Rain mm'] = clean_col(raw_df['Rain mm'], dtype='float64')
raw_df['Visibility km'] = clean_col(raw_df['Visibility km'], dtype=pd.Int64Dtype())

In [17]:
raw_df.head()

,City,Date,AVG Temperature °C,MIN Temp °C,MAX Temp °C,Dew point,Humidity,Visibility km,AVG Wind km/h,MAX Wind km/h,Wind gust km/h,Pressure mb,AVG Pressure mb,Rain mm,Phenomenas
0,Verona,2003-01-01,5.6,3.0,8.0,4.6,93.0,4,3,11,0,0.0,0.0,0.0,nebbia
1,Verona,2003-01-02,4.8,4.0,6.0,3.9,94.0,2,6,11,0,0.0,0.0,0.0,pioggia nebbia
2,Verona,2003-01-03,5.4,4.0,9.0,4.4,93.0,3,9,13,0,0.0,0.0,0.0,nebbia
3,Verona,2003-01-04,4.4,1.8,5.4,3.4,93.0,1,5,11,0,0.0,0.0,0.0,nebbia
4,Verona,2003-01-05,4.7,2.9,7.1,3.3,91.0,6,8,26,0,0.0,0.0,7.6,pioggia nebbia

In [18]:
# 14) check the string values to translate
raw_df['Phenomenas'].unique()

array(['nebbia ', 'pioggia nebbia ', 'pioggia ', 'pioggia neve nebbia ',
       'pioggia neve ', '', 'neve nebbia ', 'neve ', 'pioggia temporale ',
       'temporale ', 'pioggia temporale nebbia ', 'temporale nebbia ',
       nan, 'pioggia grandine '], dtype=object)

In [21]:
# 15) remove spaces at the start and at the end of all the words
raw_df['Phenomenas'] = raw_df['Phenomenas'].str.strip()

In [24]:
# 16) replace with the correct translation raw_df['Phenomenas] using a dictionary and inplace
raw_df['Phenomenas'].replace({'nebbia': 'fog', 'pioggia nebbia': 'rain and fog', 'pioggia':'rain',\
     'pioggia neve nebbia':'rain snow fog', 'pioggia neve':'rain snow', 'neve nebbia':'snow fog', \
        'neve':'snow', 'pioggia temporale':'rain thunderstorm','temporale':'thunderstorm',\
            'pioggia temporale nebbia':'rain thunderstorm fog', 'temporale nebbia':'thunderstorm fog',\
                'pioggia grandine':'rain hail'}, inplace=True )

In [25]:
raw_df['Phenomenas'].unique()

array(['fog', 'rain and fog', 'rain', 'rain snow fog', 'rain snow', '',
       'snow fog', 'snow', 'rain thunderstorm', 'thunderstorm',
       'rain thunderstorm fog', 'thunderstorm fog', nan, 'rain hail'],
      dtype=object)

In [ ]:
# 17) final check before exporting to csv
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7305 entries, 0 to 7304
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   City                7305 non-null   object
 1   Date                7305 non-null   datetime64[ns]
 2   AVG Temperature °C  7265 non-null   float64
 3   MIN Temp °C         7265 non-null   float64
 4   MAX Temp °C         7265 non-null   float64
 5   Dew point           7265 non-null   float64
 6   Humidity            7265 non-null   float64
 7   Visibility km       7265 non-null   Int64
 8   AVG Wind km/h       7265 non-null   Int64
 9   MAX Wind km/h       7265 non-null   Int64
 10  Wind gust km/h      7265 non-null   Int64
 11  Pressure mb         7265 non-null   float64
 12  AVG Pressure mb     7265 non-null   float64
 13  Rain mm             7265 non-null   float64
 14  Phenomenas          7265 non-null   object
dtypes: Int64(4), datetime64[ns](1), float64(8), object(2)
memory usage: 884.7+ KB

In [32]:
# 18) cleaned df to csv
df_final = raw_df.to_csv(r'Weather_df.csv')